project:
  type: website
  output-dir: docs
  render: 
    - index.qmd
  
website:
  title: "Power of ANalysis Of VAriances in steel industry"
  navbar:
    tools:
      - icon: github
        href: https://github.com/musbud/ANOVA-CuttingDiscs
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2025, Mustafa Budak"

format:
  html:
    theme: cerulean
    toc: true

editor: source



